# Generated by Django 5.2.6 on 2025-09-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can view book'), ('can_create', 'can add a book'), ('can_edit', 'can edit book information'), ('can_delete', 'can delete a book')]},
        ),
    ]
