# Generated by Django 5.2.5 on 2025-08-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_yea',
            new_name='publication_year',
        ),
    ]
